#!/bin/bash

osascript -e 'tell application id "org.jyutping.inputmethod.Jyutping" to if it is running then quit'

jyutping_executable="${DSTROOT}/Jyutping.app/Contents/MacOS/Jyutping"
"${jyutping_executable}" install

osascript -e 'tell application id "org.jyutping.inputmethod.Jyutping" to if it is running then quit'

exit 0
