#!/bin/bash

login_user=$(/usr/bin/stat -f%Su /dev/console)

# Stop the running instances
osascript -e 'tell application id "org.jyutping.inputmethod.Jyutping" to if it is running then quit'
/usr/bin/sudo -u "${login_user}" osascript -e 'tell application id "org.jyutping.inputmethod.Jyutping" to if it is running then quit'

exit 0
