#!/bin/bash

login_user=$(/usr/bin/stat -f%Su /dev/console)

# Terminate running instances
osascript -e 'tell application id "org.jyutping.inputmethod.Jyutping" to quit'
/usr/bin/sudo -u "${login_user}" osascript -e 'tell application id "org.jyutping.inputmethod.Jyutping" to quit'

exit 0
